#!/bin/bash

echo "íº€ Uploading backend to vista-ucf.com..."
scp server.js bitnami@vista-ucf.com:~/backend/

if [ $? -eq 0 ]; then
    echo "âœ… Upload successful!"
else
    echo "âŒ Upload failed!"
fi

